<?php
echo"<html>";
echo"   <head>";
echo"      <link href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/css/bootstrap.css' rel='stylesheet'>";
echo"   </head>";
echo "<body style='background: #36465d;'>";
echo "	<!-- WRAPPER -->";
echo "	<div id="wrapper">";
echo "  <div id='searchResults' class='container'>";
echo "   <div class='jumbotron'>";
echo "      <h2 style='padding-bottom: 20px;'><b>Item Search Results:</b></h2>";
echo "      <center>";
echo "      <table class='table' id='table'>";
echo "          <thead>";
echo "            <tr>";
echo "              <center>";
echo "              <th>Example 1</th>";
echo "              <th>Example 2</th>";
echo "              <th>Example 3</th>";
echo "              <th>Example 4</th>";
echo "              <th>Edit Item</th>";
echo "              <th>Add Promotion</th>";
echo "              </center>";
echo "            </tr>";
echo "          </thead>";
echo "          <tbody>";
echo "            <tr data-toggle='modal' data-target='#itemDetailModal'>";
echo "              <td><p>Result 1</p></td>";
echo "              <td><p>Result 1</p></td>";
echo "              <td><p>Result 1</p></td>";
echo "              <td><p>Result 1</p></td>";
echo "              <td><button style='padding: 10px 10px;' type='button' class='btn btn-primary' data-toggle='modal' data-target='#itemEditModal'><span class='glyphicon glyphicon-pencil'></span></button></td>";
echo "              <td><button style='padding: 10px 10px;' type='button' class='btn btn-primary' data-toggle='modal' data-target=''><span class='glyphicon glyphicon-plus'></span></button></td>";
echo "            </tr>";
echo "            <tr data-toggle='modal' data-target='#itemDetailModal'>";
echo "              <td><p>Result 1</p></td>";
echo "              <td><p>Result 1</p></td>";
echo "              <td><p>Result 1</p></td>";
echo "              <td><p>Result 1</p></td>";
echo "              <td><button style='padding: 10px 10px;' type='button' class='btn btn-primary' data-toggle='modal' data-target='#itemEditModal'><span class='glyphicon glyphicon-pencil'></span></button></td>";
echo "              <td><button style='padding: 10px 10px;' type='button' class='btn btn-primary' data-toggle='modal' data-target=''><span class='glyphicon glyphicon-plus'></span></button></td>";
echo "            </tr>";
echo "          </tbody>";
echo "      </table>";
echo "      </center>";
echo "  </div>";
echo "  </div>";
echo "  </div>";
echo"      <script src='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/js/bootstrap.min.js'></script>";
echo"   </body>";
echo"</html>";
 ?>
