<?php
echo"<html>";
echo"   <head>";
echo"      <link href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/css/bootstrap.css' rel='stylesheet'>";
echo"   </head>";
echo"   <body>";
echo"      <div class='container-fluid'>";
echo"         <div class='row'>";
echo"            <div class='col-md-12'>";
echo"               <h3 class='text-center text-primary'>PHP Form Builder</h3>";
echo"               <div class='row'>";
echo"                  <div class='col-md-6'>";
echo"                     <div class='panel panel-primary'>";
echo"                        <div class='panel-heading'>";
echo"                           <h3 class='panel-title'>Components</h3>";
echo"                        </div>";
echo"                        <div class='panel-body'>";
echo"                           <label class='col-md-4 control-label' for='input01'>Text input</label>";
echo"                           <input id='txt_textInput' type='text' placeholder='title' class='form-control input-md'>";
echo"                           <p class='help-block'></p>";
echo"                           <button id='btn_textInput' type='button' class='col-md-4 btn btn-info'>Add</button> ";
echo"                        </div>";
echo"                        <div class='panel-footer'></div>";
echo"                     </div>";
echo"                     <button type='button' class='btn btn-warning btn-block'>Reset Form</button>";
echo"                  </div>";
echo"                  <div class='col-md-6'>";
echo"                     <div class='panel panel-info'>";
echo"                        <div class='panel-heading'>";
echo"                           <h3 class='panel-title'>From Preview</h3>";
echo"                        </div>";
echo"                        <div class='panel-body'>";
echo"                        </div>";
echo"                        <div class='panel-footer'></div>";
echo"                     </div>";
echo"                     <button type='button' class='btn btn-block btn-success'>Save</button>";
echo"                  </div>";
echo"               </div>";
echo"            </div>";
echo"         </div>";
echo"      </div>";
echo"      <script src='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/js/bootstrap.min.js'></script>";
echo"   </body>";
echo"</html>";
?>
